# Site settings
name: Christophe Lecointe
description: "Not a mage, yet"
url: "https://christophelec.github.io"
title: "Christophe's page"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  christophelec
twitter_username: christophelec1
linkedin_username: christophe-lecointe-27a42328
stack_of_username: 2482711/christophelec
email: lec.christophe@gmail.com
public_key_url: "https://github.com/christophelec.keys"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars0.githubusercontent.com/u/4365804"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
